@startuml

title tomato-rpc

class ZookeeperNameService implements NameService {
    ZookeeperRegistry registry
}

class ZookeeperRegistry {
    CuratorClient curatorWrapper
    String namespace
    Charset zNodePathCharset
    ConcurrentMap<String, MicroServiceSpace> providerMap
    ConcurrentMap<MicroServiceSpace, ChildrenListener> childrenListenerMap
}

abstract class BaseRpcServer implements RpcServer {
    String host;
    int port;
    boolean useBusinessPool;
    int businessPoolSize;
}

class NettyRpcServer extends BaseRpcServer {
    DispatcherHandler dispatcherHandler;
    MetricHolder metricHolder;
    MetricHandler metricHandler;
    ServerBootstrap serverBootstrap;
    EventExecutorGroup businessGroup;
    EventLoopGroup bossGroup;
    EventLoopGroup workerGroup;
}


abstract class BaseRpcCoreService implements RpcCoreService {
    ProviderRegistry providerRegistry
    NameServer nameServer
    StubFactory stubFactory
    RpcConfig rpcConfig
}

class NettyRpcCoreService extends BaseRpcCoreService {
    NettyRpcServer server
    MetaData rpcServerMetaData
    NettyChannelHolder channelHolder
    NettyResponseHolder responseHolder
}

class BaseMicroServiceSpace implements MicroServiceSpace {
    String vip
    ConcurrentMap<MetaData, RpcInvoker> invokerRegistry
    ConcurrentMap<String, List<RpcInvoker>> sameGroupInvokerMap
}

class NettyMicroServiceSpace extends BaseMicroServiceSpace {
    RpcInvokerFactory nettyRpcInvokerFactory
    NettyChannelHolder channelHolder
    NettyResponseHolder responseHolder
}

class NettyRpcInvoker implements RpcInvoker, MessageSender {
    MetaData providerNodeMetaData
    NettyChannelHolder channelHolder
    NettyResponseHolder responseHolder
    Serializer commandSerializer
    URI uri
}

class NettyResponseFuture {
    long messageId
    CompletableFuture<Command> future
    long timeStamp
}

NettyRpcCoreService "1" *--> "1" ZookeeperNameService
ZookeeperNameService "1"*--> "1" ZookeeperRegistry
ZookeeperRegistry "1" *--> "n" MicroServiceSpace
ZookeeperRegistry "1" <--> "n" PathChildrenListener
MicroServiceSpace "1" --> "1" PathChildrenListener
MicroServiceSpace "1" *--> "n" NettyRpcInvoker
NettyResponseHolder "1" o--> "n" NettyResponseFuture
NettyRpcCoreService "1" *--> "1" NettyRpcServer

@enduml